import hashlib

def generate_finding_id(repo: str, file_path: str, line: int, vuln_type: str) -> str:
    """
    🛡️ SemanticGuard Stable ID Generator
    Ensures identical IDs are generated by the Hunting Zone (Scanner) 
    and the User Zone (Remediation Server).
    
    Args:
        repo: Repository name (e.g. 'supabase')
        file_path: Relative file path
        line: Line number where vulnerability was found
        vuln_type: The type of vulnerability (e.g. 'Fail-Open Webhook')
        
    Returns:
        str: A stable 12-character hex hash.
    """
    seed = f"{repo}:{file_path}:{line}:{vuln_type}"
    return hashlib.sha256(seed.encode()).hexdigest()[:12]
